### ISSUE TITLE
Module 4 interactive question feedback

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/exploratory-data-viz#119]
#### Question 1

This question asks what plot type is most appropriate to compare the distribution of two columns, technically, all answers are correct if one of the columns was categorical... We should edit this to be clear that we are talking about two numeric/quantitative columns, not categorical/qualitative data.

#### Question 2

This is almost identical to the question above, but specifies numeric, but does not have any overlapping options, which is strange. I think the point here is plotting two numerical columns where overplotting is an issue. Let's add that to the question. Also, let's remove area chart and put scatter plot in its place (since it is also good for plotting two distributions, but only if overplotting does not occur)

### Chapter 4 questions: Graph Analysis

Change "For which scores are pokemon most saturated in the plot?" > "For which range of pokemon attack and defence scores do we have the most observations?"

The answer is "Pokemon with average defense and attack scores.", however, I might have said low defense low and attack scores... Maybe we should change this to be "Pokemon with mid-low defense and  mid-low attack scores."?

### Chapter 5 questions: Heatmaps with Artic Penguins

Please add more scaffolding to the coding question here. It is the first one of the module, and folks likely need a reminder of all the arguments needed.

#### What flipper length and mass are most common among the penguins in our data (with the given bin size)?

These ranges are FAR too close together. Basically, we just want them to identify the bottom left-hand part, which would be 185-200 for length, and 3200-4000 for mass. Other options we could offer would be:
- 185-200 for length, and 4600-5200 for mass
- 205 - 220 for length, and 3200-4000 for mass
- 205 - 220 for length, and 4600-5200 for mass

### Chapter 7 questions: Return of the Pokemon

Please add more scaffolding to the coding question here. Also what is generation? You need to explain this for non-pokemon experts...

### Chapter 9 questions: True or False: Exploratory Data Analysis (EDA)

- First true/false Q has no false option

### Chapter 10 questions: Which graph is appropriate?

- This question title seems a bit off...

#### Question 1
- there is no correct answer here

#### Do any of the distributions look bimodal (2 bell shapes)?
- In the pop-up when folks get the right answer, can we tell them which two have the bimodal distribution?

### Chapter 13 questions: Repeating Categorical Columns Quick Questions!

- The first true/false question here is a repeat from an earlier chapter

### Chapter 14 questions: Plotting Repeated Categoricals with Penguins

Cannot select any options from the "What species of penguins and from what island are most prominent in our data?" question

**Comment by ttimbers** [comment]
@hfboyce - I did not do a thorough job of checking the incorrect messages to make sure they are correct and helpful. Please check this over when you address my feedback.

**Comment by hfboyce** [comment]
### Chapter 3 questions: Which plot is it

#### Question 1

>This question asks what plot type is most appropriate to compare the distribution of two columns, technically, all answers are correct if one of the columns was categorical... We should edit this to be clear that we are talking about two numeric/quantitative columns, not categorical/qualitative data.

Updated to include numeric/quantitative and bolded. 

#### Question 2

>This is almost identical to the question above, but specifies numeric, but does not have any overlapping options, which is strange. I think the point here is plotting two numerical columns where overplotting is an issue. Let's add that to the question. Also, let's remove area chart and put scatter plot in its place (since it is also good for plotting two distributions, but only if overplotting does not occur)

Ah yes. So I added overplotting here (I think that's what I was thinking here but forgot to put that in the question) and added scatter instead of area. 

### Chapter 4 questions: Graph Analysis

>Change "For which scores are pokemon most saturated in the plot?" > "For which range of pokemon attack and defence scores do we have the most observations?"
>
>The answer is "Pokemon with average defense and attack scores.", however, I might have said low defense low and attack scores... Maybe we should change this to be "Pokemon with mid-low defense and  mid-low attack scores."?

Changed Question and solution answer. 

### Chapter 5 questions: Heatmaps with Artic Penguins

>Please add more scaffolding to the coding question here. It is the first one of the module, and folks likely need a reminder of all the arguments needed.

Added the arguments or the argument values now for this question

#### What flipper length and mass are most common among the penguins in our data (with the given bin size)?

> These ranges are FAR too close together. Basically, we just want them to identify the bottom left-hand part, which would be 185-200 for length, and 3200-4000 for mass. Other options we could offer would be:
> - 185-200 for length, and 4600-5200 for mass
> - 205 - 220 for length, and 3200-4000 for mass
> - 205 - 220 for length, and 4600-5200 for mass

Updated to suggested options. 

### Chapter 7 questions: Return of the Pokemon

> Please add more scaffolding to the coding question here. Also what is generation? You need to explain this for non-pokemon experts...

Added this: 

For those less familiar with Pokemon, a Pokemon's generation is determined by the ara it was introduced. For example the first generation spans Pokemon characters that were released in video games from 1996-1999. The 7th generation are Pokemon introduced from games released between 2016-2019.

According to [Wikipedia](https://en.wikipedia.org/wiki/Gameplay_of_Pok%C3%A9mon#Pok%C3%A9mon_types), A Pokémon's type is *"an elemental attribute determining the strengths and weaknesses of each Pokémon and its moves. Pokémon take double damage from attacking moves of types they are weak to and half damage from moves they resist. These type matchups offset one another in rock–paper–scissors-style relationships."*

 And more scaffolding in the exercise. 

### Chapter 9 questions: True or False: Exploratory Data Analysis (EDA)

> - First true/false Q has no false option

Fixed! 

### Chapter 10 questions: Which graph is appropriate?

> - This question title seems a bit off...

Changed to "Exploring EDA"

#### Question 1
> - there is no correct answer here

The correct answer is "Creating a predictive model from the data" which wasn't showing up because of formatting (uuhhggg) 

### Chapter 11 questions: Plotting numeric columns with Penguins

#### Do any of the distributions look bimodal (2 bell shapes)?
- In the pop-up when folks get the right answer, can we tell them which two have the bimodal distribution?
-  Added " Maybe look at the `culmen_length_mm` and `flipper_length_mm` distributions. " and " The `culmen_length_mm` and `flipper_length_mm` distributions both appear to be bimodal."  in the popups. 

### Chapter 13 questions: Repeating Categorical Columns Quick Questions!

> - The first true/false question here is a repeat from an earlier chapter

 My bad 🤦‍♀️ 
### Chapter 14 questions: Plotting Repeated Categoricals with Penguins

> Cannot select any options from the "What species of penguins and from what island are most prominent in our data?" question

Fixed this!
