### ISSUE TITLE
 Module 5 interactive question feedback

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/exploratory-data-viz#121]
### Chapter 3: Which Graph is Effective?

Question 1: Incorrect messages are not really that helpful or informative (not even sure they are correct).

Question 2: I would argue that plot b should have an additional category called other countries, with the sum of counts from the countries we show here. Then we effectively show all the data we have (counts of 0 are data!)

### Chapter 5: True or False: Titles and Formatting (T/F)?

Last true false question sentence doesn't make sense: "Not very axis and legend needs to have a title."

### Chapter 7: Formatting Fun!

Did we not have an image of the culmen that we added in another slide or question to remind/tell folks what it is. This is def far from common knowledge. Can we add it here again?

There is too much code to be entered here. Can we just give them the base plot code and then have them fill in the formatting bit (that is the focus of this slide deck anyways).

We should have some follow-up question about how formatting this plot made it more effective for communication.

### Chapter 9: True or False: Transformations

- The correct message with the first true/false question should also communicate the caveat that we should be careful doing this, as we risk inflating  the appearances differences.

- The last true/false question is problematic. The answer seems to have to do with 0's but there is no mention of 0's in the data in the question posed.

### Chapter 10: Transformations and Presentations

Question 1: Is this really what clip does? I thought it just removed points on a chart that were outside of the axis range?

Question 2: The incorrect hints could be more helpful, especially for the first one.

### Chapter 11: Using Transformations in Action!

Again, for the coding questions (both here), let's just give them the plot code, and just have them fill in the stuff relevant to formatting.

Question (follow up MCQ): I did not make the mapping easily with Symmetric Logarthmic and `Symlog`. Maybe we need to add the code args beside these english terms in the MCQ options? They only had a single slide on this.

In the last follow-up question, can we make the hint more helpful for negative (maybe hint that they should pay attention to the direction?)

### Chapter 14: Colour Coordination Questions

Question 1: The incorrect MCQ and the hints don't make them seem wrong... I think we need to tweak the question to something like, when is it most effective/important to use custom colour schemes?

Question 2: Change to " **After** how many colours (approximately by a rule of thumb) should you begin to reconsider colour as an effective channel to represent your data? 

(currently that question is a bit confusing/tricky)

### Chapter 15: Adding some Colour to Penguins

There is too much code to be entered here. Can we just give them the base plot code and then have them fill in the formatting bit (that is the focus of this slide deck anyways).

Can we plot something other than culmen length? What about flipper length and body mass? That is something easier for folks to visualize the shape of the penguin by. Also the title should not just be about one axis of the data. It should be about both, and the species, otherwise why not just make a density plot for the one column of interest.

The follow-up should be focused on the formatting (topic of the module).

### Chapter 18: Colouring by Numbers Question

Question 1 is confusing having the colours repeated twice, and with different icons. Can we just use the one without the emojis? It is clearer and simpler. 

### Chapter 19: Playing with Colour

There is too much code to be entered here. Can we just give them the base plot code and then have them fill in the formatting bit (that is the focus of this slide deck anyways).

I think this plot is not that effective. Can we lose the points and colour the line with the diverging colour scheme?

Typo here: "Can you think of why this might occur**s**?"

Question - why Ottawa weather instead of somewhere in BC? Most of our students will be from BC..."

Follow-up question should be about the plot formatting.

### Chapter 23: Precipitation Contemplation

There is too much code to be entered here. Can we just give them the base plot code and then have them fill in the formatting bit (that is the focus of this slide deck anyways).

Again, why Ottawa data?

Again, the follow-up question should be aout the plot formatting (keep your eye on the prize).

**Comment by hfboyce** [comment]
### Chapter 3: Which Graph is Effective?

> Question 1: Incorrect messages are not really that helpful or informative (not even sure they are correct).

Made the popups more informative. 

> Question 2: I would argue that plot b should have an additional category called other countries, with the sum of counts from the countries we show here. Then we effectively show all the data we have (counts of 0 are data!)

 I did add a column named `other`? It's in the plot! 

### Chapter 5: True or False: Titles and Formatting (T/F)?

> Last true false question sentence doesn't make sense: "Not very axis and legend needs to have a title."

WHOOPS! Changed to "Not all axes and legends needs to have a title."

### Chapter 7: Formatting Fun!

> Did we not have an image of the culmen that we added in another slide or question to remind/tell folks what it is. This is def far from common knowledge. Can we add it here again?

Added.

>There is too much code to be entered here. Can we just give them the base plot code and then have them fill in the formatting bit (that is the focus of this slide deck anyways).

> We should have some follow-up question about how formatting this plot made it more effective for communication.

Added this: 
![image](https://user-images.githubusercontent.com/42727648/111210124-1b018e80-858a-11eb-8cb8-957bab199d2f.png)


### Chapter 9: True or False: Transformations

> - The correct message with the first true/false question should also communicate the caveat that we should be careful doing this, as we risk inflating  the appearances differences.

Added this -> 

- You've been paying attention here! It's important to know that we should be careful we we do this, as sometimes we risk inflating differences among categories or measures. 

and 
- Although we should be careful we we do this, as sometimes we risk inflating differences among categories or measures but sometimes we need to see values within a certain range to identify any variable or relationships within the data. 

> - The last true/false question is problematic. The answer seems to have to do with 0's but there is no mention of 0's in the data in the question posed.

Changed the question to this: 
*Log transforming an axis is a good option to use if there is a large range of values to displayed that incorporates zero and you don't want to compress the smaller values into the bottom of the graph.*

### Chapter 10: Transformations and Presentations

> Question 1: Is this really what clip does? I thought it just removed points on a chart that were outside of the axis range?
Updated question to -> Which of the following arguments will exclude points from a plot?

> Question 2: The incorrect hints could be more helpful, especially for the first one.

Updated. 

### Chapter 11: Using Transformations in Action!

> Again, for the coding questions (both here), let's just give them the plot code, and just have them fill in the stuff relevant to formatting.

Added. 

> Question (follow up MCQ): I did not make the mapping easily with Symmetric Logarthmic and `Symlog`. Maybe we need to add the code args beside these english terms in the MCQ options? They only had a single slide on this.

Added code beside the options ex:

"Symmetric Logarithmic, <code>alt.Scale(type='symlog')</code>"

> In the last follow-up question, can we make the hint more helpful for negative (maybe hint that they should pay attention to the direction?)

example 

Are you sure here? Maybe maybe take a look at the direction the points are forming (low to high?).

### Chapter 14: Colour Coordination Questions

> Question 1: The incorrect MCQ and the hints don't make them seem wrong... I think we need to tweak the question to something like, when is it most effective/important to use custom colour schemes?

Now. -> When is it most effective to use custom colour schemes?

> Question 2: Change to " **After** how many colours (approximately by a rule of thumb) should you begin to reconsider colour as an effective channel to represent your data? (currently that question is a bit confusing/tricky)

Changed. 

### Chapter 15: Adding some Colour to Penguins

>There is too much code to be entered here. Can we just give them the base plot code and then have them fill in the formatting bit (that is the focus of this slide deck anyways).

Added the arguments.

Can we plot something other than culmen length? What about flipper length and body mass? That is something easier for folks to visualize the shape of the penguin by. Also the title should not just be about one axis of the data. It should be about both, and the species, otherwise why not just make a density plot for the one column of interest.

> Now plotting body mass and fixed the title. the plot now looks like this: 

![image](https://user-images.githubusercontent.com/42727648/111217910-55235e00-8593-11eb-845d-56235672aeb1.png)



> The follow-up should be focused on the formatting (topic of the module).

The follow up is now 

If you removed the colour channel, would you be able to answer the question *"Which two penguin species are the most similar size in terms of mass and flipper length"* ? 

### Chapter 18: Colouring by Numbers Question

>Question 1 is confusing having the colours repeated twice, and with different icons. Can we just use the one without the emojis? It is clearer and simpler. 

Done.

### Chapter 19: Playing with Colour

> There is too much code to be entered here. Can we just give them the base plot code and then have them fill in the formatting bit (that is the focus of this slide deck anyways).

Added arguments and code. 

> I think this plot is not that effective. Can we lose the points and colour the line with the diverging colour scheme?

@ttimbers Help here please! 

> Typo here: "Can you think of why this might occur**s**?"

Fixed. 

> Question - why Ottawa weather instead of somewhere in BC? Most of our students will be from BC..."

Changed to Kamloops. 

> Follow-up question should be about the plot formatting.
Added some context now.  

### Chapter 23: Precipitation Contemplation

> There is too much code to be entered here. Can we just give them the base plot code and then have them fill in the formatting bit (that is the focus of this slide deck anyways).

Added some code now.


> Again, why Ottawa data?

Changed to Kamloops. 

> Again, the follow-up question should be aout the plot formatting (keep your eye on the prize).

Changed to 
"In this plot would it make sense to sort the values on the x axis instead of highlighting the month?"
